from __future__ import annotations


TYPE_LABELS = {
    "movie": "영화",
    "music": "음악",
    "book": "도서",
}

ROLE_TAGS = {
    "안전": ["위로", "평온", "회복", "자기돌봄"],
    "공감": ["공감", "관계", "그리움", "성찰", "위로"],
    "안정": ["평온", "휴식", "고요", "명상", "위로"],
    "회복": ["회복", "위로", "희망", "재출발", "자기돌봄"],
    "재도전": ["성장", "진로", "도전", "자존감", "재출발"],
    "자기효능감": ["성장", "자존감", "자기표현", "진로"],
    "호기심": ["우주", "여행", "탐험", "지식", "과학", "상상"],
    "몰입": ["일상", "문화", "상상", "성찰", "음악"],
    "확장": ["우주", "여행", "탐험", "지식", "미래"],
    "가벼운 탐색": ["일상", "휴식", "평온", "기쁨"],
    "전환": ["가벼움", "전환", "유쾌함", "휴식", "발견"],
    "증폭": ["기쁨", "즐거움", "밝음", "신남", "유쾌함"],
    "축하": ["성취", "뿌듯함", "축하", "자신감", "희망"],
    "음미": ["평온", "감사", "안도감", "따뜻함", "잔잔함"],
    "영감": ["희망", "도전", "미래", "성장", "자신감"],
    "유지": ["일상", "평범함", "휴식", "저부담", "잔잔함"],
    "발견": ["무료함", "가벼운 관심", "일상", "탐색", "문화"],
    "배경": ["배경친화", "저부담", "휴식", "집", "음악"],
    "가벼운 성찰": ["사색적", "잔잔함", "일상", "자기이해", "평온"],
    "탐색": ["우주", "과학", "여행", "예술", "호기심"],
    "학습": ["과학", "우주", "지식", "학습", "미래"],
}

ROLE_PURPOSES = {
    "안전": "위험 감정을 낮추고 안전감을 먼저 확보",
    "공감": "현재 감정이 이해받는 느낌 제공",
    "안정": "불안과 과흥분을 낮추는 차분한 전환",
    "회복": "다시 움직일 수 있는 정서적 여지 만들기",
    "재도전": "자기효능감과 다음 행동의 감각 회복",
    "자기효능감": "내가 다시 해볼 수 있다는 감각 강화",
    "호기심": "현재 관심사를 즐거운 탐색으로 확장",
    "몰입": "복잡한 감정에서 잠시 벗어나는 몰입 제공",
    "확장": "관심 주제를 넓히고 새로운 연결 만들기",
    "가벼운 탐색": "부담 없이 문화 콘텐츠에 접근",
    "전환": "현재 기분을 과하지 않게 환기",
    "증폭": "좋은 기분을 밝고 자연스럽게 확장",
    "축하": "잘 해낸 일을 가볍게 축하",
    "음미": "좋은 여운을 천천히 오래 머물게 하기",
    "영감": "다음 가능성과 동기를 부드럽게 확장",
    "유지": "잔잔한 하루의 흐름을 깨지 않게 유지",
    "발견": "부담 없이 새 취향을 발견",
    "배경": "쉬는 시간에 곁에 둘 저부담 콘텐츠",
    "가벼운 성찰": "일상을 가볍게 돌아보는 정리감 제공",
    "탐색": "관심 주제를 더 넓게 살펴보기",
    "학습": "궁금한 주제를 조금 더 알아가는 방향",
}

SITUATION_TAGS = {
    "관계 상실/이별": ["이별", "관계", "상실", "회복", "공감"],
    "관계 속 연결/즐거움": ["관계", "친구", "기쁨", "음미", "증폭"],
    "관계 갈등 또는 연결 욕구": ["관계", "대화", "공감", "자기이해"],
    "평가 상황 이후의 자신감 저하": ["발표", "실패", "자존감", "진로", "성장", "회복"],
    "성과 압박과 시험 스트레스": ["시험", "학교", "성장", "회복", "자존감"],
    "성취 이후 다음 단계 부담": ["성취", "발표", "불안", "진로", "자기효능감"],
    "성취와 여운": ["성취", "기쁨", "회복", "평온"],
    "여유로운 긍정 일상": ["기쁨", "즐거움", "평온", "음미", "증폭", "휴식", "일상", "음식"],
    "진로/미래 탐색": ["진로", "미래", "성장", "자기이해", "도전"],
    "우주와 탐험에 대한 새 관심": ["우주", "탐험", "과학", "미래", "경외"],
    "일상 이탈과 여행 욕구": ["여행", "탐색", "휴식", "자기이해"],
    "일상 감정 기록": ["일상", "자기이해", "평온", "회복"],
    "잔잔한 일상": ["일상", "집", "휴식", "음식", "저부담", "배경친화"],
    "가벼운 무료함과 탐색 욕구": ["일상", "무료함", "발견", "가벼운 관심"],
}

ROLE_WEIGHTS = {
    "공감": {
        "emotion_match": 0.25,
        "situation_fit": 0.19,
        "semantic_similarity": 0.15,
        "emotion_regulation": 0.13,
        "safety_score": 0.12,
        "affect_alignment": 0.07,
        "personal_fit": 0.06,
        "novelty": 0.03,
    },
    "안정": {
        "safety_score": 0.22,
        "emotion_regulation": 0.18,
        "calm_fit": 0.16,
        "support_fit": 0.14,
        "role_fit": 0.12,
        "cognitive_load_fit": 0.1,
        "semantic_similarity": 0.04,
        "personal_fit": 0.04,
    },
    "회복": {
        "emotion_regulation": 0.18,
        "recovery_potential": 0.18,
        "support_fit": 0.17,
        "situation_fit": 0.15,
        "semantic_similarity": 0.12,
        "safety_score": 0.1,
        "personal_fit": 0.06,
        "novelty": 0.04,
    },
    "재도전": {
        "situation_fit": 0.2,
        "role_fit": 0.19,
        "emotion_regulation": 0.14,
        "semantic_similarity": 0.12,
        "personal_fit": 0.11,
        "affect_alignment": 0.1,
        "safety_score": 0.08,
        "novelty": 0.04,
        "cognitive_load_fit": 0.02,
    },
    "확장": {
        "topic_match": 0.2,
        "role_fit": 0.18,
        "semantic_similarity": 0.16,
        "novelty": 0.13,
        "cognitive_load_fit": 0.12,
        "affect_alignment": 0.1,
        "safety_score": 0.07,
        "personal_fit": 0.04,
    },
    "가벼운 탐색": {
        "safety_score": 0.19,
        "calm_fit": 0.16,
        "novelty": 0.16,
        "semantic_similarity": 0.13,
        "role_fit": 0.13,
        "emotion_regulation": 0.1,
        "cognitive_load_fit": 0.07,
        "personal_fit": 0.04,
        "topic_match": 0.02,
    },
    "전환": {
        "safety_score": 0.18,
        "novelty": 0.16,
        "calm_fit": 0.14,
        "emotion_regulation": 0.14,
        "role_fit": 0.13,
        "semantic_similarity": 0.12,
        "cognitive_load_fit": 0.09,
        "topic_match": 0.04,
    },
    "증폭": {
        "emotion_match": 0.2,
        "affect_alignment": 0.18,
        "role_fit": 0.16,
        "emotion_regulation": 0.14,
        "semantic_similarity": 0.12,
        "safety_score": 0.1,
        "personal_fit": 0.06,
        "novelty": 0.04,
    },
    "축하": {
        "situation_fit": 0.2,
        "role_fit": 0.18,
        "affect_alignment": 0.16,
        "emotion_match": 0.14,
        "semantic_similarity": 0.12,
        "safety_score": 0.1,
        "personal_fit": 0.06,
        "novelty": 0.04,
    },
    "음미": {
        "affect_alignment": 0.18,
        "calm_fit": 0.16,
        "emotion_regulation": 0.15,
        "safety_score": 0.13,
        "role_fit": 0.12,
        "semantic_similarity": 0.1,
        "support_fit": 0.1,
        "personal_fit": 0.06,
    },
    "영감": {
        "topic_match": 0.18,
        "role_fit": 0.17,
        "affect_alignment": 0.15,
        "semantic_similarity": 0.14,
        "emotion_regulation": 0.12,
        "cognitive_load_fit": 0.1,
        "safety_score": 0.08,
        "personal_fit": 0.06,
    },
    "유지": {
        "calm_fit": 0.2,
        "cognitive_load_fit": 0.17,
        "safety_score": 0.16,
        "role_fit": 0.14,
        "affect_alignment": 0.12,
        "semantic_similarity": 0.08,
        "personal_fit": 0.07,
        "novelty": 0.06,
    },
    "발견": {
        "novelty": 0.2,
        "cognitive_load_fit": 0.16,
        "safety_score": 0.14,
        "role_fit": 0.14,
        "semantic_similarity": 0.13,
        "affect_alignment": 0.1,
        "personal_fit": 0.08,
        "topic_match": 0.05,
    },
    "배경": {
        "cognitive_load_fit": 0.22,
        "calm_fit": 0.2,
        "safety_score": 0.16,
        "role_fit": 0.16,
        "emotion_regulation": 0.1,
        "personal_fit": 0.08,
        "semantic_similarity": 0.04,
        "novelty": 0.04,
    },
    "가벼운 성찰": {
        "calm_fit": 0.16,
        "affect_alignment": 0.15,
        "semantic_similarity": 0.14,
        "role_fit": 0.14,
        "cognitive_load_fit": 0.12,
        "safety_score": 0.12,
        "topic_match": 0.1,
        "personal_fit": 0.07,
    },
    "탐색": {
        "topic_match": 0.22,
        "semantic_similarity": 0.18,
        "role_fit": 0.16,
        "affect_alignment": 0.13,
        "novelty": 0.12,
        "cognitive_load_fit": 0.09,
        "safety_score": 0.06,
        "personal_fit": 0.04,
    },
    "학습": {
        "topic_match": 0.24,
        "semantic_similarity": 0.18,
        "role_fit": 0.17,
        "cognitive_load_fit": 0.14,
        "novelty": 0.1,
        "affect_alignment": 0.08,
        "safety_score": 0.05,
        "personal_fit": 0.04,
    },
}

DEFAULT_ROLE_WEIGHTS = {
    "semantic_similarity": 0.15,
    "situation_fit": 0.15,
    "support_fit": 0.14,
    "emotion_regulation": 0.14,
    "role_fit": 0.12,
    "safety_score": 0.1,
    "affect_alignment": 0.08,
    "recovery_potential": 0.06,
    "calm_fit": 0.04,
    "personal_fit": 0.02,
}

AMPLIFYING_NEGATIVE_TAGS = {"절망", "비극", "분노", "상실", "우울", "고립", "어두움"}
RESTORATIVE_TAGS = {"회복", "위로", "평온", "희망", "따뜻함", "기쁨", "안도감", "잔잔함"}
HIGH_TENSION_TAGS = {"긴장", "압박", "생존", "두려움", "분노", "비극", "고립"}
LOW_TENSION_TAGS = {"평온", "휴식", "고요", "명상", "위로", "따뜻함", "저부담", "배경친화", "평범함"}
VULNERABLE_EMOTIONS = {"슬픔", "불안", "무기력", "외로움", "창피함", "후회"}
